microsoft/DirectXTK12

Inc/DirectXHelpers.h
Src/LinearAllocator.cpp

DirectXHelpers.h updated with public ``AlignUp`` and ``AlignDown`` helpers.

AlignUp, AlignDown helpers

---

DirectXTK_Desktop_2015_Win10.vcxproj
DirectXTK_Desktop_2015_Win10.vcxproj.filters
DirectXTK_Desktop_2017_Win10.vcxproj
DirectXTK_Desktop_2017_Win10.vcxproj.filters
DirectXTK_Windows10.vcxproj
DirectXTK_Windows10.vcxproj.filters
DirectXTK_Windows10_2015.vcxproj
DirectXTK_Windows10_2015.vcxproj.filters
DirectXTK_XboxOneXDK_2015.vcxproj
DirectXTK_XboxOneXDK_2015.vcxproj.filters
DirectXTK_XboxOneXDK_2017.vcxproj
DirectXTK_XboxOneXDK_2017.vcxproj.filters
Inc/Effects.h
Src/EffectFactory.cpp
Src/ModelLoadSDKMESH.cpp
Src/PBREffectFactory.cpp
Src/SDKMesh.h

Adds ``PBREffectFactory`` class and ``sdkmesh2`` materials loading

SDKMESH2 export support for PBR materials

---

Audio/SoundStreamInstance.cpp
CMakeLists.txt
DirectXTK_Desktop_2017_Win10.vcxproj
DirectXTK_Desktop_2017_Win10.vcxproj.filters
DirectXTK_Desktop_2019_Win10.vcxproj
DirectXTK_Desktop_2019_Win10.vcxproj.filters
DirectXTK_Windows10_2017.vcxproj
DirectXTK_Windows10_2017.vcxproj.filters
DirectXTK_Windows10_2019.vcxproj
DirectXTK_Windows10_2019.vcxproj.filters
DirectXTK_XboxOneXDK_2017.vcxproj
DirectXTK_XboxOneXDK_2017.vcxproj.filters
Inc/BufferHelpers.h
Src/BufferHelpers.cpp
Src/LoaderHelpers.h
Src/PlatformHelpers.h

Added a new header with ``CreateStaticBuffer`` and ``CreateTextureFromMemory``

BufferHelpers added to the toolkit

---

Audio/WAVFileReader.cpp

Fixes microsoft/DirectXTK12#83.

Fix reading of WAV loop region length

---

Inc/EffectPipelineStateDescription.h
Inc/RenderTargetState.h
Inc/SimpleMath.h
Inc/SpriteBatch.h
Src/AlignedNew.h
Src/Bezier.h
Src/EffectTextureFactory.cpp
Src/GraphicsMemory.cpp
Src/Model.cpp
Src/ModelLoadSDKMESH.cpp
Src/ScreenGrab.cpp
Src/SimpleMath.cpp
Src/SpriteBatch.cpp

Trying out the code-base with a GNUC compiler I encountered a number of issues that I've cleaned up.
Also realized that ``RenderTargetState`` was missing a ``DXGI_SWAP_CHAIN_DESC1`` ctor.

Conformance and minor code cleanup

---

Inc/Effects.h
Inc/GeometricPrimitive.h
Src/AlphaTestEffect.cpp
Src/BasicEffect.cpp
Src/DebugEffect.cpp
Src/DualTextureEffect.cpp
Src/EffectFactory.cpp
Src/EnvironmentMapEffect.cpp
Src/GeometricPrimitive.cpp
Src/NormalMapEffect.cpp
Src/PBREffect.cpp
Src/PBREffectFactory.cpp
Src/Shaders/CompileShaders.cmd
Src/Shaders/DebugEffect.fx
Src/Shaders/NormalMapEffect.fx
Src/Shaders/PBREffect.fx
Src/Shaders/Structures.fxh
Src/Shaders/Utilities.fxh
Src/SkinnedEffect.cpp

* DebugEffect, NormalMapEffect, PBREffect updated to support instancing using a XMFLOAT3X4 transform in the vertex data
* Added DrawInstanced method to GeometricPrimitive

DebugEffect, NormalMapEffect, PBREffect updated with instancing support

---

Inc/DirectXHelpers.h
Inc/EffectPipelineStateDescription.h
Inc/Model.h
Src/BasicPostProcess.cpp
Src/DDSTextureLoader.cpp
Src/DescriptorHeap.cpp
Src/DirectXHelpers.cpp
Src/EffectFactory.cpp
Src/EffectPipelineStateDescription.cpp
Src/PBREffectFactory.cpp
Src/ResourceUploadBatch.cpp
Src/ScreenGrab.cpp
Src/d3dx12.h

For details on this change, see [this blog post](https://devblogs.microsoft.com/oldnewthing/20220113-00/?p=106152).
Related to https://github.com/microsoft/DirectX-Headers/issues/72

Update to support ABI for MinGW in DX Agility SDK v1.606.3

---

.nuget/directxtk12_desktop_2019.nuspec
.nuget/directxtk12_uwp.nuspec
HISTORY.md
README.md

* DirectXHelpers updated with **CreateUnorderedAccessView**, **CreateRenderTargetView**, **CreateBufferShaderResourceView**, and **CreateBufferUnorderedAccessView** helpers
* Added **EnableLighting** method to ``EffectFactory`` to support creating unlit model materials
* GamePad, Keyboard, and Mouse headers have ``USING_XINPUT``, ``USING_GAMEINPUT``, ``USING_WINDOWS_GAMING_INPUT`` defines
* Updates for *GameInputCreate* failure handling on PC
* Updated D3DX12 internal copy with latest changes from DirectX-Headers GitHub
* CMake project updated to require 3.20 or later
* CMake and MSBuild project updates
* Minor MinGW code changes
* Added Azure Dev Ops Pipeline YAML files
* Test suite updated with CTest support

December 15, 2022

---

Audio/WAVFileReader.cpp

Fixes an out-of-bounds read bug in the WAVFileReader that could be a potential security issue when given untrusted WAV files.

Fix out-of-bounds read bug in WAVFileReader

---

.nuget/directxtk12_desktop_2019.nuspec
.nuget/directxtk12_uwp.nuspec
CMakeLists.txt
HISTORY.md
LICENSE
README.md

* Fixed warnings when using GPU-based validation on PC
* Mouse relative mode now accumulates multiple delta updates per frame. Added new optional but recommended method ``EndOfInputFrame``.
* Fixed out-of-bounds read bug in the .WAV file reader.
* Additional checks added to DDSTextureLoader for planar video formats.
* CMake project updates

February 6, 2023

---

LICENSE
README.md
SECURITY.md
build/DirectXTK12-GitHub-CMake-Dev17.yml
build/DirectXTK12-GitHub-CMake.yml
build/DirectXTK12-GitHub-Dev17.yml
build/DirectXTK12-GitHub-GDK-Dev17.yml
build/DirectXTK12-GitHub-GDK.yml
build/DirectXTK12-GitHub-MinGW.yml
build/DirectXTK12-GitHub-SDK-prerelease.yml
build/DirectXTK12-GitHub-SDK-release.yml
build/DirectXTK12-GitHub-Test-Dev17.yml
build/DirectXTK12-GitHub-Test.yml
build/DirectXTK12-GitHub.yml

Update for latest files for MIT license and the SECURITY statement.
> Also tweaked CI/PR build triggers.

Update for latest files from the Microsoft GitHub template

---

Audio/AudioEngine.cpp

The **Resume** method threw a C++ exception if the XAudio2 StartEngine failed. It should switch to silent mode if it fails.
In addition, I added handling for the required audio device being 'locked' by exclusive mode ownership.

DirectX Tool Kit for Audio fix for failing Resume

---

Audio/AudioEngine.cpp

Fix warning from recent *DirectX Tool Kit for Audio* work.

Minor warning fix

---

.nuget/directxtk12_desktop_2019.nuspec
.nuget/directxtk12_uwp.nuspec
HISTORY.md
README.md

* *DirectX Tool Kit for Audio* updates
* Reworked audio device enumeration for XAudio 2.9 to use MMDeviceEnumerator rather than Windows Runtime APIs
* ``GetOutputFormat`` now reports sample rate and bit-depth from the audio device properties
* New method ``GetOutputSampleRate`` added to return the input sample rate of the mastering voice
* ``Resume`` now handles device failure by switching to silent mode
* CMake project updates
* Retired VS 2017 legacy Xbox One XDK projects

March 30, 2023

---

.nuget/directxtk12_desktop_2019.nuspec
.nuget/directxtk12_uwp.nuspec
HISTORY.md
README.md

* Updated D3DX12 internal copy with latest changes from DirectX-Headers GitHub
* CMake project updates and fixes for clang/LLVM v16 warnings

April 28, 2023

---

.nuget/directxtk12_desktop_2019.nuspec
.nuget/directxtk12_uwp.nuspec
HISTORY.md
README.md

* Root Signature updates to resolve some warnings from Xbox PIX
* CMake project updates

June 2023 release

---

CMakeLists.txt
CMakePresets.json
build/CopyASan.targets
build/DirectXTK12-OneFuzz.yml
build/OneFuzzConfig.json

Provides file-fuzzing for DDS file reader.

Add OneFuzz build pipeline

---

.gitignore
Audio/SoundCommon.cpp
Audio/WAVFileReader.cpp
Audio/WaveBankReader.cpp

Also includes some minor code review for DirectX Tool Kit for Audio.

Added more bounds checking to WAVFileReader

---

Audio/SoundStreamInstance.cpp
Audio/WaveBankReader.cpp
Src/ModelLoadCMO.cpp
Src/Mouse.cpp
Src/ScreenGrab.cpp
build/DirectXTK12-SDL.yml

Add SDL build pipeline

---

build/DirectXTK12-GitHub-GDK.yml
build/DirectXTK12-GitHub-MinGW.yml
build/DirectXTK12-GitHub-Test-Dev17.yml
build/DirectXTK12-GitHub-Test.yml
build/DirectXTK12-OneFuzz.yml
build/DirectXTK12-SDL.yml

* Use CodeQL 3000
* Minimize disk space usage for the cmake pipeline with tests
* YAML code review

Update ADO build pipelines

---

Audio/AudioEngine.cpp
Audio/DynamicSoundEffectInstance.cpp
Audio/SoundStreamInstance.cpp
Audio/WaveBankReader.cpp
Inc/Audio.h
Inc/DirectXHelpers.h
Inc/GamePad.h
Inc/Keyboard.h
Inc/Mouse.h
Inc/ScreenGrab.h
Inc/WICTextureLoader.h
Src/GamePad.cpp
Src/Keyboard.cpp
Src/Mouse.cpp
Src/PlatformHelpers.h
Src/pch.h

Guard pragmas specific to MSVC-like compilers

fix warning for MSVC pragma syntax.

---

Audio/SoundCommon.cpp
CMakePresets.json
build/CompilerAndLinker.cmake
build/DirectXTK12-GitHub-CMake-Dev17.yml
build/DirectXTK12-GitHub-CMake.yml
build/DirectXTK12-GitHub-GDK-Dev17.yml
build/DirectXTK12-GitHub-MinGW.yml
build/DirectXTK12-GitHub-Test.yml
build/DirectXTK12-GitHub.yml
build/DirectXTK12-OneFuzz-Coverage.yml
build/SetupBWOI.cmd
build/SetupBWOI.targets

Also fixes build issue with XboxOne CMake scenarios.
Includes an ADO pipeline update to validate GDKX builds using CMake.

Fix build warnings and errors with GDKX using Clang

---

CMakePresets.json
build/DirectXTK12-GitHub-Test-Dev17.yml

Adds ARM64EC presets per the instructions on [Microsoft Learn](https://learn.microsoft.com/en-us/windows/arm/arm64ec-build).

CMake updated to build ARM64EC

---

build/DirectXTK12-GitHub-GDK-Dev17.yml
build/DirectXTK12-GitHub-GDK.yml
build/DirectXTK12-GitHub-SDK-prerelease.yml
build/DirectXTK12-GitHub-SDK-release.yml
build/DirectXTK12-GitHub-Test-Dev17.yml
build/Directory.Build.props

Various minor code review updates for ADO build pipelines.

Build pipeline updates

---

build/DirectXTK12-GitHub-GDK-Dev17.yml
build/DirectXTK12-GitHub-GDK.yml
build/DirectXTK12-GitHub-SDK-prerelease.yml
build/DirectXTK12-GitHub-SDK-release.yml
build/Directory.Build.props
build/SetupBWOI.targets

Includes some cleanup for BWOI scenarios

ADO pipeline for SDK builds

---

Audio/SoundCommon.cpp

Minor bug in implementation of #241.

Fixed bugs in AudioEmitter/AudioListener IsValid

---

.nuget/directxtk12_desktop_2019.nuspec
.nuget/directxtk12_uwp.nuspec
Audio/AudioEngine.cpp
CHANGELOG.md
CMakeLists.txt
README.md

* C++17 `std::byte` support for `FromMemory` functions
* GamePad, Keyboard, and Mouse _GameInput_ implementation now supports both v0 and v1 of the API
* SimpleMath changes for Vector2/Vector3 operators to speed up performance particularly in debug builds
* *DirectX Tool Kit for Audio* changes:
* Added more audio engine flags to control X3DAudio usage: `AudioEngine_DisableLFERedirect`, `AudioEngine_DisableDopplerEffect`, `AudioEngine_ZeroCenter3D`
* Repurposed `SoundEffectInstance_UseRedirectLFE` from an internal flag to a per voice override
* Added `SoundEffectInstance_ZeroCenter3D` as a per voice override
* Bug fixes for recent ``IsValid`` methods
* Code review particularly to remove Windows 7 and Windows 8.0 code paths in shared code
* CMake project updates including support for …

March 20, 2025

---

.azuredevops/pipelines/DirectXTK12-GitHub-GDK-Dev17.yml
.azuredevops/pipelines/DirectXTK12-GitHub-GDK.yml
.azuredevops/pipelines/DirectXTK12-GitHub-MinGW.yml
.azuredevops/pipelines/DirectXTK12-GitHub-SDK-prerelease.yml
.azuredevops/pipelines/DirectXTK12-GitHub-SDK-release.yml
.azuredevops/pipelines/DirectXTK12-GitHub-Test-Dev17.yml
.azuredevops/pipelines/DirectXTK12-GitHub-Test.yml

Moved `ADOFeedGUID`, `ADOFeedURL`, `GDK_EDITION` and `VCPKG_TAG` to a shared variable group.

Update ADL YAML to use shared variables

---

Src/Keyboard.cpp
Src/Mouse.cpp

Change the way GameInput callbacks are handled for mouse/keyboard with multiple flags

Change the way GameInput callbacks are handled for mouse/keyboard

---

.azuredevops/pipelines/DirectXTK12-OneFuzz-Meshes.yml

OneFuzz runs on the 1st of the month seeding DDS files.
OneFuzz runs on the 15th of the month seeding CMO, SDKMESH, and VBO files.
Both runs go for a week.

Add more OneFuzz pipelines

---

.azuredevops/pipelines/DirectXTK12-GitHub-CMake-Dev17.yml
.azuredevops/pipelines/DirectXTK12-GitHub-CMake.yml
.azuredevops/pipelines/DirectXTK12-GitHub-MinGW.yml
.azuredevops/pipelines/DirectXTK12-OneFuzz-Meshes.yml
.azuredevops/pipelines/DirectXTK12-OneFuzz.yml
.github/copilot-instructions.md
.gitignore
Audio/SoundCommon.cpp
CMakeLists.txt
Inc/Audio.h
Inc/DescriptorHeap.h
Inc/Keyboard.h
Src/BasicPostProcess.cpp
Src/DebugEffect.cpp
Src/DescriptorHeap.cpp
Src/DualPostProcess.cpp
Src/EffectCommon.h
Src/EffectFactory.cpp
Src/EffectPipelineStateDescription.cpp
Src/EffectTextureFactory.cpp
Src/EnvironmentMapEffect.cpp
Src/GeometricPrimitive.cpp
Src/Keyboard.cpp
Src/Model.cpp
Src/PrimitiveBatch.cpp
Src/SpriteBatch.cpp
Src/SpriteFont.cpp
Src/ToneMapPostProcess.cpp

* Marked a few more functions as ``noexcept``
* Added more ``std::invalid_argument`` checks for null device to ctors
* Added `ENABLE_CODE_PROFILING` option to CMake
> windows-2022 image removed 10.0.22000.0 SDK

Code review and CoPilot instructions update
