microsoft/DirectXTK12

- Inc/GeometricPrimitive.h
- Inc/GraphicsMemory.h
- Inc/Model.h
- Src/BasicPostProcess.cpp
- Src/DualPostProcess.cpp
- Src/EffectCommon.h
- Src/GeometricPrimitive.cpp
- Src/GraphicsMemory.cpp
- Src/ModelLoadSDKMESH.cpp
- Src/ModelLoadVBO.cpp
- Src/PrimitiveBatch.cpp
- Src/SpriteBatch.cpp
- Src/ToneMapPostProcess.cpp
This adds basic multi-GPU support to DirectX Tool Kit. It primary requires a per-device ``GraphicsMemory`` singleton, and passing an explicit device to ``GeometricPrimitive`` and ``Model``.
> mGPU support for DirectX Tool Kit

- Audio/WAVFileReader.cpp
- Audio/WaveBankReader.cpp
- Inc/Audio.h
- Inc/Model.h
- Src/AlphaTestEffect.cpp
- Src/BasicPostProcess.cpp
- Src/Bezier.h
- Src/CommonStates.cpp
- Src/DDSTextureLoader.cpp
- Src/DemandCreate.h
- Src/EffectCommon.cpp
- Src/GamePad.cpp
- Src/Geometry.cpp
- Src/GraphicsMemory.cpp
- Src/LoaderHelpers.h
- Src/Model.cpp
- Src/PlatformHelpers.h
- Src/PrimitiveBatch.cpp
- Src/ResourceUploadBatch.cpp
- Src/ScreenGrab.cpp
- Src/SpriteBatch.cpp
- Src/SpriteFont.cpp
- Src/WICTextureLoader.cpp
- Src/XboxDDSTextureLoader.cpp
- Src/dds.h
- Src/pch.h
The change here is to make the _DirectX Tool Kit_ math code build correctly with DirectXMath 3.12 or later when using ``_XM_NO_XMVECTOR_OVERLOADS_``.
> Fix compiler errors (Clang 6)

- Inc/Effects.h
- Inc/GraphicsMemory.h
- Inc/Model.h
- Inc/ResourceUploadBatch.h
- Src/EffectTextureFactory.cpp
- Src/Model.cpp
- Src/ModelLoadSDKMESH.cpp
- Src/ModelLoadVBO.cpp
- Src/ResourceUploadBatch.cpp
In the original implementation, all Model vertex buffers and index buffers are allocated by ``GraphicsMemory``. This means that they are in a upload heap which is accessible to both the CPU and GPU, equivalent to the Direct3D 11 version of ``USAGE_DYNAMIC``. This is simple and easy to use, but has performance impacts--which on Xbox One can be quite noticeable due to the caching behavior.
This change adds an optional call to ``LoadStaticBuffers`` which uses a ``ResourceUploadBatch`` to create static VB/IBs for rendering copying the data from the loaded ``GraphicsMemory`` resources. This is equivalent to ``USAGE_DEFAULT`` in Direct3D 11.
The ``ModelMeshPart`` now contains four new members:
* ``staticVertexBuffer``: If set, then this vertex buffer is used for rendering as the VB in the view. …
> Model::LoadStaticBuffers to use static VB/IB instead of dynamic

- Src/ModelLoadSDKMESH.cpp
There is no direct DXGI equivalent to the legacy Direct3D 9 vertex format ``D3DDECLTYPE_DEC3N``. It's a signed 10:10:10 normalized format. Some legacy DirectX SDK samples for DX10 / DX 11 just treat it as ``DXGI_FORMAT_R10G10B10A2_UNORM`` which kind of works.
This update uses that hack for DirectXTK, but emits a warning a debug builds.
> SDKMESH updated to load models using legacy DEC3N compressed normals

- Inc/ResourceUploadBatch.h
- Src/DDSTextureLoader.cpp
- Src/LoaderHelpers.h
- Src/ResourceUploadBatch.cpp
- Src/WICTextureLoader.cpp
The list of formats supported for the UAV path was assuming ``D3D12_FEATURE_DATA_D3D12_OPTIONS.TypedUAVLoadAdditionalFormats`` was always set. This change makes sure that is validated.
Also allows optional device support for other UAV formats to cover almost all the same formats that DX11 could support for autogen mips.
> Had to make ``IsSupportedForGenerateMips`` a non-static method, which required some code refactoring for the texture loaders.
> Autogen format support made more robust

- Inc/GraphicsMemory.h
- Src/GraphicsMemory.cpp
- Src/LinearAllocator.cpp
- Src/LinearAllocator.h
Added a few more ``DebugTrace`` statements around failure points with GraphicsMemory to help in debugging out-of-memory scenarios.
Also applied some code review feedback to the memory code.
> Additional debugging output for GraphicsMemory

- Inc/ScreenGrab.h
- Src/ScreenGrab.cpp
With the new 'flip' style presentation model for Windows 10 or later, you don't actually use ``*_SRGB`` on the backbuffer format. Therefore, the resulting ``PNG`` screenshot would be washed out.
This adds a new optional paraemeter to allow forcing the sRGB metadata.
> Added optional forceSRGB parameter to SaveWICTextureToFile

- Inc/Model.h
- Src/ModelLoadSDKMESH.cpp
- Src/ModelLoadVBO.cpp
A few minor feature requests and some other workflows I have made me revisit the Model loader APIs. This rearranges the optional device value first to be more consistent with DirectXTK--it can be null.
Also added two features:
* Allowing models that are larger than the 'required resource support size' constants for Direct3D
* Converting material color information in ``SDKMESH`` from sRGB colorspace to linear.
> Breaking change to ``Model::CreateFrom*`` methods but it's easy to fix up. Just put the ``device`` or ``nullptr`` first.
> Added ModelLoaderFlags

- Src/SpriteFont.cpp
Modifications to the MeasureString and MeasureDrawBounds methods to allow for factoring in whitespace, and ensuring that the measurement changes make sense, such as giving whitespace a height equal to the font's line spacing.
> This is related to the new ``ignoreWhiteSpace`` defaulted parameter and not manifest when 'true' is used.
> Modifications to the MeasureString and MeasureDrawBounds methods

- Inc/GeometricPrimitive.h
- Inc/ResourceUploadBatch.h
- Src/GeometricPrimitive.cpp
- Src/ResourceUploadBatch.cpp
The ResourceUploadBatch as originally implemented only worked on ``DIRECT`` command queues, which are the kind created by DeviceResources.
This PR adds supports for both COPY and COMPUTE command queues as an option.
* ``COPY`` queues only support loading. They cannot support GenerateMips
* `` COMPUTE`` queues can support the current features.
> The only other supported command queue types are ``VIDEO_*`` which are not relevant here.
> ResourceUploadBatch updated to support copy & compute queues

- Inc/SpriteBatch.h
- Src/SpriteBatch.cpp
SpriteBatch has two rendering modes;
* The first is to use a static sampler built into the rootsignature. This is the default behavior and provides the easiest usage.
* The second is to provide a heap-based sampler for the SpriteBatch creation. In this case, it uses a rootsig that references the sampler from an active heap.
In the second case, I originally only let you set it at creation time. My primary motivation was to avoid having to have many permutations of the sprite VS/PS shaders and root-signature.
One of the advantages of the heap-based sampler is that it can be changed easily between rendering batch. I therefore added support in the form of an alternative Begin() method to let you provide a new heap-based sampler to use with rendering.
> SpriteBatch updated with sampler-version of Begin

- .nuget/directxtk12-config.cmake.in
- CMakeLists.txt
This PR updates the CMake support in DirectX Tool Kit to support ``find_package(directxtk12 CONFIG)``:
```
find_package(directxtk12 CONFIG REQUIRED)
target_link_libraries(foo Microsoft::DirectXTK12)
```
> CMake package support

- Inc/Audio.h
- Inc/BufferHelpers.h
- Inc/DDSTextureLoader.h
- Inc/DescriptorHeap.h
- Inc/DirectXHelpers.h
- Inc/EffectPipelineStateDescription.h
- Inc/Effects.h
- Inc/GeometricPrimitive.h
- Inc/GraphicsMemory.h
- Inc/Model.h
- Inc/PostProcess.h
- Inc/PrimitiveBatch.h
- Inc/ScreenGrab.h
- Inc/SimpleMath.h
- Inc/SpriteBatch.h
- Inc/SpriteFont.h
- Inc/WICTextureLoader.h
- Inc/XboxDDSTextureLoader.h
- Src/pch.h
Reviewed all the C++ standard library header usage and normalized usage for improved conformance.
* ``size_t`` requires ``cstddef``
* ``memcpy``, ``memcpy_s`` is officially in ``cstring``
* Use ``cassert`` instead of ``assert.h``
> The non-standard malloc.h is still being included for ``_aligned_malloc`` / ``_aligned_free``. To be conformant, I should update it to use ``aligned_alloc`` and ``free`` when building for C++17 which is in ``cstdlib``.
Also trimmed trailing whitespace in these files.
> Code review for standard library header usage

- Src/ScreenGrab.cpp
It is unable to call `GetHeapProperties` for reserved resources. But such info required only for `READBACK` resources optimization, capture code should not fail for reserved resources in this case.
```
D3D12 ERROR: ID3D12Resource2::ID3D12Resource::GetHeapProperties: GetHeapProperties can not be called on a resource created with the CreateReservedResource API. [ RESOURCE_MANIPULATION ERROR #901: GETHEAPPROPERTIES_INVALIDRESOURCE]
```
Invalid desc for resolved resource copied from the original multisample resource with `Alignment = D3D12_DEFAULT_MSAA_RESOURCE_PLACEMENT_ALIGNMENT`, which fails creation call.
> Fix of CaptureTexture for Reserved and MultiSample resources

- CMakeLists.txt
- DirectXTK_Desktop_2019_Win10.vcxproj
- DirectXTK_GDK_2017.vcxproj
- DirectXTK_GDK_2019.vcxproj
- DirectXTK_Windows10_2019.vcxproj
- Src/Shaders/CompileShaders.cmd
At this point, Shader Model 6 is mature and broadly supported, so I've switched these projects to use it by default:
```
DirectXTK_Desktop_2019_Win10.vcxproj
DirectXTK_GDK_2017.vcxproj
DirectXTK_GDK_2019.vcxproj
DirectXTK_Windows10_2019.vcxproj
```
The ``CMakeLists.txt`` now has a new build option which defaults to ON called ``BUILD_DXIL_SHADERS`` to control use of DXC vs. FXC.
> For the Gaming.Xbox.*.x64 configurations in ``DirectXTK_GDK_201x.vcxproj`` it was already always using Shader Model 6. These updates are for Gaming.Desktop.x64
The Desktop and Windows 10 VS 2017 projects were *not* updated to use DXIL because they are set up for the Windows 10 SDK (17763) which was the last version to come included with VS 2017, and this version has some known bugs with the DXC compiler.
> Default to DXC/DXIL Shader Model 6 for CMake and Windows SDK 19041

- Inc/PostProcess.h
- Src/Shaders/ToneMap.fx
- Src/Shaders/Utilities.fxh
- Src/ToneMapPostProcess.cpp
Updated ToneMapPostProcess to allow dynamic control over the color primary rotation matrix used for HDR10 signal processing. It defaults to using the 'standard' Rec.709 to Rec.2020 color primary rotation just as before. This adds a ``SetColorRotation`` method with an overloads.
> ToneMapPostProcess updated with color rotation transform control

- Src/ResourceUploadBatch.cpp
Hello!
Thank you for providing such a great tool. While using this tool, I found that the Windows handle keeps increasing when many resources are uploaded. 
I found that the handle created for the fence event in the 'ResourceBatchUpload' was not closed, so I modified the code.
> unclosed handle in Src/ResourceUploadBatch.cpp

- Inc/Model.h
- Src/Model.cpp
- Src/ModelLoadSDKMESH.cpp
- Src/PlatformHelpers.h
Adds the **ModelBone** class to *DirectX Tool Kit*'s **Model** support, with loading from ``SDKMESH`` files.
* Includes the bone transforms and inverse bind pose transforms needed for both rigid-body and skinned animation.
* The ``ModelLoader_IncludeBones`` flag must be specified to have the loaders include the bone information if present.
**ModelMeshPart** updated with optional bone index for rigid-body animation, and optional bone-influences for indirect vertex mapping for bones (used by ``SDKMESH``).
**ModelMesh** updated with **Draw** method overloads for rigid-body transform drawing.
**Model** and **ModelMesh** updated with **DrawSkinned** methods.
**Model** updated with **CopyAbsoluteBoneTransformsTo**, **CopyAbsoluteBoneTransforms**, **CopyBoneTransformsFrom**, and …
> Adding ModelBone support for transform hierarchies

- CMakeLists.txt
- DirectXTK_Desktop_2017_Win10.vcxproj
- DirectXTK_Desktop_2017_Win10.vcxproj.filters
- DirectXTK_Desktop_2019_Win10.vcxproj
- DirectXTK_Desktop_2019_Win10.vcxproj.filters
- DirectXTK_Desktop_2022_Win10.vcxproj
- DirectXTK_Desktop_2022_Win10.vcxproj.filters
- DirectXTK_GDK_2017.vcxproj
- DirectXTK_GDK_2017.vcxproj.filters
- DirectXTK_GDK_2019.vcxproj
- DirectXTK_GDK_2019.vcxproj.filters
- DirectXTK_Windows10_2017.vcxproj
- DirectXTK_Windows10_2017.vcxproj.filters
- DirectXTK_Windows10_2019.vcxproj
- DirectXTK_Windows10_2019.vcxproj.filters
- DirectXTK_XboxOneXDK_2017.vcxproj
- DirectXTK_XboxOneXDK_2017.vcxproj.filters
- Inc/Model.h
- Src/ModelLoadCMO.cpp
In the original port of *DirectX Tool Kit for DX12*, CMO was not moved over as it was considered associated with the Direct3D 11 specific DGSL shader editor VS feature.
This ports the CMO model loader--including animation bones support--to DirectX 12, but only supports BasicEffect or SkinnedEffect materials with a single texture. This matches what *DirectX Tool Kit for DX11* did if you used a standard effect factory instead of the DGSLEffectFactory.
> The one tricky bit with the DirectX 12 version is that if you load a model that contains skinned meshes, but uses materials without a texture, the model will fail to render by default. In DirectX 11, I automatically applied a default 1x1 texture to SkinnedEffect in this case. It's easy to fix-up with some code I'll include in the docs to …
> DirectX Tool Kit for DX 12 updated to load CMO models

- Audio/SoundStreamInstance.cpp
- Audio/WaveBank.cpp
- Audio/WaveBankReader.cpp
- Audio/WaveBankReader.h
- Inc/Audio.h
*DirectX Tool Kit for Audio* wavebank streaming updated to support Advanced Format (4Kn) format drives which have a 4096 sector size vs. the classic 2048 that worked for DVDs, older generation HDDs, and Advanced Format drives in 512e mode.
> WaveBank streaming updated to support Advanced Format (4Kn)

- Inc/SimpleMath.h
- Inc/SimpleMath.inl
This adds a ``ToEuler`` method to both Matrix and Quaternion that returns a Vector3 with the x-axis, y-axis, and z-axis rotations required to create the rotation.
This uses the same rotational order as the yaw-pitch-roll functions which is "rotates about y-axis (yaw), then x-axis (pitch), then z-axis (roll)"
Also added overloads of the ``CreateFromYawPitchRoll`` methods for both Matrix and Quaternion that takes the angles as a Vector3 in the same order.
> Added ToEuler methods to Matrix and Quaternion

- Inc/SimpleMath.h
- Inc/SimpleMath.inl
- Src/SimpleMath.cpp
SimpleMath was based on the methods in the XNA Game Studio math classes. There are a few Quaternion functions that have been added to other math libraries that would be useful to add for Quaternion:
* ``RotateTowards`` which moves a quaternion toward a target quaternion limited by a maximum delta angle
* ``FromToRotation`` which computes a relative rotation between two direction vectors
* ``LookRotation`` which computes a rotation which aligns to a direction and up vector
* ``Angle`` which computes the angle between two quaternion rotations
> Add more Quaternion methods for SimpleMath

- Inc/DescriptorHeap.h
Returning size_t just means it has to be further cast to UINT when it's put into a D3DX12_CPU_DESCRIPTOR_HANDLE struct.
> Minor fix to DescriptorHeap::Increment() to return uint32_t.

- Audio/WAVFileReader.cpp
- Audio/WaveBankReader.cpp
- Src/BinaryReader.cpp
- Src/LoaderHelpers.h
- Src/ScreenGrab.cpp
- Src/WICTextureLoader.cpp
- Src/XboxDDSTextureLoader.cpp
- Src/d3dx12.h
Per the C++ Standard:
> the identifiers that begin with an underscore followed by an uppercase letter are reserved;
I had this in my backlog for some time, but never got around to it until now. Clang v13 (which is in VS 2022 Update 1) has added a new warning for this case: ``-Wreserved-identifier``
> Convert internal functions to use Internal namespace instead of leading underscore

- Audio/AudioEngine.cpp
- Inc/GamePad.h
- Inc/Keyboard.h
- Inc/Mouse.h
- Src/GamePad.cpp
- Src/Keyboard.cpp
- Src/Mouse.cpp
- Src/pch.h
* Cleaned up the code a bit to simplify the various ``#if`` conditions
* Added ``WM_ACTIVATE`` to Win32 Keyboard
* Added ``Mouse::SetWindow`` and ``Keyboard::ProcessMessage`` methods for GameInput implementation to simplify integration instructions
* Fixed bug with UWP Mouse so it doesn't track the HWHEEL as the normal WHEEL
* Legacy Xbox One XDK support now requires April 2018, May 2018, or June 2018.
> Input refactoring and cleanup

- .nuget/DirectXTK12-config.cmake.in
- CMakeLists.txt
- CMakePresets.json
- Inc/DirectXHelpers.h
- Inc/GamePad.h
- Inc/ScreenGrab.h
- Inc/SimpleMath.h
- Src/AlignedNew.h
- Src/GamePad.cpp
- Src/PlatformHelpers.h
- Src/ResourceUploadBatch.cpp
- Src/pch.h
Adds support to DirectX Tool Kit CMake file to build with MinGW.
```
x64-Debug-MinGW
x64-Release-MinGW
x86-Debug-MinGW
x86-Release-MinGW
```
Makes use of VCPKG for DirectXMath and DirectX-Headers since the MinGW has minimal versions of these libraries. Requires the ``VCPKG_ROOT`` envvar set.
This is being done to improve compiler conformance for the code.
> CMake support added for building with MinGW

- CMakeLists.txt
- CMakePresets.json
- Src/Shaders/CompileShaders.cmd
VCPKG now has a [directx-dxc](https://github.com/microsoft/vcpkg/tree/master/ports/directx-dxc) port which provides the latest DXC.EXE compiler binary fetched from GitHub. This updates the *DirectX Tool Kit for DX12* CMakeLists to utilize this port when building with VCPKG.
> At the moment, the **directx-dxc** port only runs on x64-windows. It will find port for other target platforms by using the x64-windows host triplet as a 'tools' port. We do not use the CMake target from it, so this works fine.
> ARM64 native support is planned for the next update on GitHub of DXC.
> Update CMake to use DXC from VCPKG

- CMakeLists.txt
- Inc/CommonStates.h
- Inc/DDSTextureLoader.h
- Inc/DirectXHelpers.h
- Inc/Effects.h
- Inc/GeometricPrimitive.h
- Inc/GraphicsMemory.h
- Inc/Model.h
- Inc/PostProcess.h
- Inc/PrimitiveBatch.h
- Inc/SpriteBatch.h
- Inc/SpriteFont.h
- Inc/VertexTypes.h
- Inc/WICTextureLoader.h
- README.md
- Src/EffectCommon.h
- Src/PrimitiveBatch.cpp
- Src/ScreenGrab.cpp
- Src/WICTextureLoader.cpp
This adds use of C++11 inline namespaces to wrap types that have *DirectX Tool Kit for DX11* equivalents with the same name. This would allow for 'mixed' use of the *DirectX Tool Kit for DX11* and *DirectX Tool Kit for DX12* in the same exe without link-time conflicts. This also requires making sure there is only one set of the 'shared' code modules like GamePad, etc. which is supported via a CMake build option `BUILD_MIXED_DX11=ON`
It has no client-code impacts, although all client code would need rebuilt to link against a static library build with these changes.
> Add use of C++11 inline namespaces

- Inc/GamePad.h
- Inc/Keyboard.h
- Inc/Mouse.h
- Src/GamePad.cpp
- Src/Keyboard.cpp
- Src/Mouse.cpp
By default the input implementation choice is made by the platform defines. This allows the ``USING_GAMEINPUT``, ``USING_WINDOWS_GAMING_INPUT``, and ``USING_XINPUT`` defines to override this rather than just indicating the choice.
The defines can also be used to force the header when used in client code to match whatever choice was used to build the library in cases where the defaults don't match.
> Added explicit GAMEINPUT vs. WGI vs. XINPUT preprocessor overrides

- CMakeLists.txt
This PR introduces a new CMake build option ``DISABLE_MSVC_ITERATOR_DEBUGGING`` to allow clients to disable MSVC's iterator debugging in Debug configuration since this is now the 'default' for clang/LLVM for Windows builds even when not using the ``clang-cl`` driver.
> Add CMake build option DISABLE_MSVC_ITERATOR_DEBUGGING

- Src/DDSTextureLoader.cpp
- Src/LoaderHelpers.h
Added height alignment validation for planar video formats. This reports these issues earlier as NOT_SUPPORTED instead of the E_INVALIDARG error that is eventually returned from the Direct3D API.
> Additional checks for video formats for DDSTextureLoader

- build/DirectXTK12-GitHub-MinGW.yml
Update for latest XAudio2Redist NuGet release. 1.2.11 includes bug fixes to make the headers link correctly when using the MinGW toolset.
> Update MinGW YAML for XAudio2Redist 1.2.11

- Inc/DirectXHelpers.h
- Src/BufferHelpers.cpp
- Src/DDSTextureLoader.cpp
- Src/GeometricPrimitive.cpp
- Src/Model.cpp
- Src/SpriteBatch.cpp
- Src/SpriteFont.cpp
- Src/WICTextureLoader.cpp
- build/DirectXTK12-GitHub-MinGW.yml
When **SetEnableGPUBasedValidation** is enabled on Windows, the initial state for a resource will result in a harmless but noisy warning.
```
D3D12 WARNING: ID3D12Device::CreateCommittedResource: Ignoring InitialState D3D12_RESOURCE_STATE_COPY_DEST. Buffers are effectively created in state D3D12_RESOURCE_STATE_COMMON. [ STATE_CREATION WARNING #1328: CREATERESOURCE_STATE_IGNORED]
```
The fix is to use the ``COMMON`` state initially and allow it to promote automatically.
> Since common state promotion/decay is optional on Xbox, it must continue to use COPY_DEST as the initial state for this platform.
> Fix warnings when using GPU-based validation on PC

- Inc/Mouse.h
- Src/Mouse.cpp
For high-sensitivity mice, ``WM_INPUT`` is getting called multiple times per frame and the original implementation of RAW mouse for Win32 was only recording the most recent dx/dy. This change now accumulates delta from ``WM_INPUT`` in relative mode.
For this to work correctly, each time ``Mouse::GetState`` is called in relative movement mode, the accumulated delta is reset so the assumption is that this is called _once per frame_.
Since this does not cover all usage scenarios, there is new optional method for Mouse **EndOfInputFrame** that should be called once per render call. This turns off the 'auto-reset' behavior of **GetState** and instead clears it once per frame in this method instead.
> Mouse needs to accumulate delta between calls to GetState

- CMakeLists.txt
With VS 2022 17.5 or later I use ``/Zc:templateScope`` for conformance, but this fails to build with current Microsoft GDK with Xbox release if you make use of **wrl.h** or **wrl/events.h**.
This updates the CMake to avoid using the conformance switch on Xbox targets.
> GDKX not currently compatible with /Zc:templateScope

- Audio/AudioEngine.cpp
- Inc/Audio.h
XAudio 2.8 on Windows 8 required the use of Windows Runtime APIs for device enumeration. XAudio2.9 on Windows 10 (18362)  or later and all versions of XAudio2Redist support both Windows Runtime device ids -and- standard WASAPI device ids.
This PR reworks the device enumeration to use WASAPI enumeration for most cases, and WinRT enumeration for the UWP platform and for XAudio 2.8 scenarios only.
In addition, this PR returns correct values for ``GetOutputFormat().Format.wBitsPerSample`` where possible. It previously always returned a value of 16.
> For Windows Server 2019 (17763) or other older Windows 10 scenarios, the recommendation is to use XAudio2Redist instead of the built-in XAudio 2.9.
> Rework audio device enumeration for XAudio2.9

- CMakeLists.txt
- build/DirectXTK12-GitHub-GDK-Dev17.yml
- build/DirectXTK12-GitHub-GDK.yml
- build/DirectXTK12-GitHub-SDK-prerelease.yml
- build/DirectXTK12-GitHub-SDK-release.yml
Support for "SHA256" hashing of PDBs is required for SDL compliance, and is supported by VS 2019 or later. Support for this switch was added to clang/LLVM for Windows v16 which is coming in VS 2022 17.6.
> Also need a workaround applied for a problem with NuGet 6.6 and NuGetCommand@2 using custom.
> CMake update to use /ZH:SHA_256 for clang v16 or later

- CMakeLists.txt
- Src/d3dx12.h
When building with CMake and VS 2022 Update 5 or later, I make use of ``/Zc:templateScope`` for conformance validation. This is, however, not compatible with the Windows SDK prior to the Windows SDK (22000) build.
> Also fixes a build break in the Windows SDK preview validation pipelines.
> Fix CMake problem with /Zc:templateScope on older Windows SDKs

- build/DirectXTK12-config.cmake.in
The CMakeLists.txt no longer mandates both **directxmath** and **directx-headers** packages be found unless building with MinGW. This fixes the behavior for CMake clients consuming this package from VCPKG.
> CMake target file fix

- build/DirectXTK12-config.cmake.in
With the changes to make use of DirectXMath & DirectX-Headers 'optional' for VCPKG scenarios unless using MinGW, the generated targets file needed more robust handling of these targets.
> CMake targets fixes for optional vs. required packages

- Src/d3dx12.h
Also fixes a -Wold-school-cast warning from clang.
> D3DX12 update to fix errors when using preview Windows SDKs

- Audio/AudioEngine.cpp
- Audio/SoundEffect.cpp
- Audio/WaveBank.cpp
- CMakeLists.txt
- Inc/Audio.h
- Inc/Effects.h
- Inc/Model.h
- Inc/ScreenGrab.h
- Inc/SpriteFont.h
- Src/DDSTextureLoader.cpp
- Src/Model.cpp
- Src/ModelLoadCMO.cpp
- Src/ModelLoadSDKMESH.cpp
- Src/ModelLoadVBO.cpp
- Src/ScreenGrab.cpp
- Src/SpriteFont.cpp
- Src/WICTextureLoader.cpp
- build/DirectXTK12-GitHub-CMake-Dev17.yml
- build/DirectXTK12-GitHub-CMake.yml
Some usage scenarios build the library with ``/Zc:wchar_t-`` but mix both ``unsigned short*`` and ``wchar_t*`` client usage. For this *opt-in* build scenario, the library will link with both the non-native and native ``wchar_t``.
Note this works for general use, but not necessarily all use cases. For example, all the effect and texture factory virtual methods are defined only using the type that matches the compiler setting for the library, as there's no easy way to provide an adapter for these. There are also some edge-cases like ``SpriteFont::GetDefaultCharacter`` that you can't use a link-time adapter because the overloading rules don't allow only differing by return type.
> Also fixes some Code Analysis warnings as you can't use ``_In_opt_`` with ``std::function<>``.
> Add NO_WCHAR_T build option to CMake

- Src/pch.h
The CMake scenario already disables the new clang v16 warning, but if you upgrade the VCXPROJ project to clangcl, it reappears.
> Suppress some additional clang v16 warnings when upgrading to clangcl

- .nuget/directxtk12_uwp.nuspec
- CMakePresets.json
- DirectXTK_Windows10_2019.sln
- DirectXTK_Windows10_2019.vcxproj
- DirectXTK_Windows10_2022.sln
- DirectXTK_Windows10_2022.vcxproj
- Src/DDS.h
- build/DirectXTK12-GitHub-CMake-Dev17.yml
- build/DirectXTK12-GitHub-CMake.yml
- build/DirectXTK12-GitHub-Dev17.yml
- build/DirectXTK12-GitHub-SDK-prerelease.yml
- build/DirectXTK12-GitHub-SDK-release.yml
- build/DirectXTK12-GitHub-Test.yml
- build/DirectXTK12-GitHub.yml
- build/Directory.Build.props
32-bit ARM support is being deprecated for the UWP platform, and support is being removed from newer ARM-based CPUs and the Windows 11 OS.
> 32-bit ARM was never officially supported for Win32 desktop development.
See [Microsoft Learn](https://learn.microsoft.com/windows/arm/arm32-to-arm64)
> AArch32 (ARM32) architecture deprecation

- Inc/GraphicsMemory.h
- README.md
- Src/GeometricPrimitive.cpp
- Src/GraphicsMemory.cpp
- Src/ModelLoadCMO.cpp
- Src/ModelLoadSDKMESH.cpp
- Src/ModelLoadVBO.cpp
- Src/PrimitiveBatch.cpp
- Src/ScreenGrab.cpp
- Src/SpriteBatch.cpp
Adds ``enum GraphicsMemory::Tag`` and a defaulted parameter for ``GraphicsMemory::Allocate`` to take a tag.
> These tags are currently unused on all other platforms.
> GraphicsMemory updated to support Xbox PIX memory tracking

- Audio/SoundCommon.cpp
- Inc/Audio.h
Added *EnableLinearCurves* and *EnableInverseSquareCurves* helpers. *EnableDefaultCurves* still work as before turning off distance attenuation as it does in XACT.
> Additional curve helpers for AudioEmitter

- Src/WICTextureLoader.cpp
When using mipmap auto-generation with WIC source files that are BGRA format, the format will not be supported if the driver does not report support for both `D3D12_FEATURE_DATA_D3D12_OPTIONS.TypedUAVLoadAdditionalFormats` and `.StandardSwizzle64KBSupported`.
The "workaround" is to use the force RGBA32 which is always supported, but this combination of flags is not properly validated. This fixes that scenario.
> Fix WIC loader bug when using autogen+force-rgba32

- build/DirectXTK12-GitHub-MinGW.yml
- build/DirectXTK12-GitHub-Test-Dev17.yml
The latest **windows-2022** ADO image no longer includes the Ninja build tool by default. It had been pulled in by another component as a dependency but is no longer there. The official solution is to install ninja using the Chocolatey package manager which part of the base image.
The latest update upgraded MinGW-W64 to 12.2, so I no longer need to explicitly install it for that pipeline.
> Update build pipelines for recent changes to windows-2022 ADO images

- Src/Shaders/CompileShaders.cmd
- Src/pch.h
Per [this blog post](https://devblogs.microsoft.com/directx/announcing-hlsl-2021/) there is a new HLSL language syntax supported by DXC. This will eventually become the default, so we explicitly opt into it for the toolkit shaders for Xbox.
> For all Windows SDKs prior to 22621, the ``-HV 2021`` switch results in "unknown version". As such, we don't use it yet for PC.
Also updated minimum guards for GDK versions (June 2021 for GDK, March 2022 for GDXK)
> Enable HLSL 2021 language model for DXC on Xbox

- Inc/GraphicsMemory.h
- Src/Model.cpp
- Src/ResourceUploadBatch.cpp
This fixes a missed header function in GraphicsMemory for Xbox which needed ``__cdecl`` (see #180)
The library uses explicit ``__cdecl`` decoration in the header to ensure that on x86/x64, the calling convention is consistent with how the library is built (i.e. it uses /Gd for x64/x86) no matter which default calling-convention the client code is using.
In most cases you only need to decorate the header declaration of a function, but you also need to decorate the definition in a few specific cases:
* Free functions (i.e. not class member methods)
* Virtual overrides
> Fixed missing __cdecl on ReportCustomMemoryAlloc static method

- Inc/BufferHelpers.h
- Src/BufferHelpers.cpp
The ``CreateStaticBuffer`` helper is designed to create a DEFAULT resource and initialize it with data uploaded via a ResourceUploadBatch.
This PR adds ``CreateUploadBuffer`` which creates an UPLOAD resource and initializes it via a direct Map/Unmap cycle since it's CPU accessible. If you pass a ``nullptr`` for the data, it just creates the UPLOAD resource.
This also adds ``CreateUAVBuffer`` which is just a simple way to create a UAV resource since that's common for DXR and DirectCompute scenarios.
> Add CreateUploadBuffer and CreateUAVBuffer helpers

- Audio/WAVFileReader.cpp
When looking at a RIFF/IFF FORM, the containing chunk size includes the 4 bytes of the FORM tag. This fixes the bounds computation to take this into account.
> RIFF parsing bounds fix for WAVFileReader

- DirectXTK_GDK_2019.vcxproj
- DirectXTK_GDK_2022.vcxproj
- build/DirectXTK12-OneFuzz.yml
* Added a target to the GDK projects to provide a more actionable error message in the case of the GDK not being installed -or- the VS integration is missing.
* Updated YAML because the `-o` parameter is ambiguous for modern PowerShell.
> Update GDK projects and ADO pipelines

- Audio/AudioEngine.cpp
- Audio/DynamicSoundEffectInstance.cpp
- Audio/SoundStreamInstance.cpp
- Audio/WaveBankReader.cpp
- CMakeLists.txt
- Src/Keyboard.cpp
- Src/LoaderHelpers.h
- Src/Mouse.cpp
- Src/d3dx12.h
The clang/LLVM toolset currently does not respect the ``float_control`` pragma for SSE instrinsics. Therefore, the use of ``/fp:fast`` is not recommended on clang/LLVM until this issue is fixed. See [55713](https://github.com/llvm/llvm-project/issues/55713).
Also includes updates for warnings found under clang v18.1.0 RC
> Includes an update for the latest changes to D3DX12.H
> Workaround clang/LLVM bug with /fp:fast+SSE+float_control

- CMakeLists.txt
- CMakePresets.json
- Inc/GamePad.h
- Inc/Keyboard.h
- Inc/Mouse.h
- Src/WICTextureLoader.cpp
* `/Qspectre` is MSVC only
* IntelLLVM should be treated the same as Clang
* Intel Classic Compiler:
* ICC does not default to ``/EHsc`` like MSVC
* Doesn't support ``/ZH:SHA_256``
* Uses `/arch`
* Known linker issues with C++17, so use C++14 instead
* Whitespace cleanup
> Intel Classic Compiler is officially deprecated. I only support it here to improve conformance validation.
> Update CMake to work with Intel compilers

- CMakePresets.json
- Inc/DirectXHelpers.h
The PC debug layer will warn in places where you are using specific resource states when common-state promotion handles it. On Xbox, common-state is opt-in. To support this, there are some defines in DirectXHelpers.h to provide the optimal state for Xbox vs. PC. This PR two more.
> Add c_initialRead/UAVTargetState to help with PC vs. Xbox warnings

- build/DirectXTK12-GitHub-Test.yml
> Fix failure with GitHub test pipeline

- Src/ScreenGrab.cpp
- Src/WICTextureLoader.cpp
I used the ``DirectX::Internal`` namespace in some other contents, and in particular I used an inline namespace ``DirectX::DX12`` with an ``Internal`` namespace. This confuses some compilers and resulted in build failures. As a solution, I just renamed the internal namespaces to something more unique.
> Rename Internal namespace to ToolKitInternal for some conformance issues

- .github/workflows/codeql.yml
- .github/workflows/main.yml
- .github/workflows/msbuild.yml
- .github/workflows/msvc.yml
- .github/workflows/test.yml
- CMakePresets.json
- build/DirectXTK12-GitHub-CMake-Dev17.yml
- build/DirectXTK12-GitHub-CMake.yml
- build/DirectXTK12-GitHub-Dev17.yml
- build/DirectXTK12-GitHub-GDK.yml
- build/DirectXTK12-GitHub-MinGW.yml
- build/DirectXTK12-GitHub-Test-Dev17.yml
- build/DirectXTK12-GitHub-Test.yml
- build/DirectXTK12-GitHub.yml
- build/DirectXTK12-SDL.yml
While most pipelines are hosted on ADO, this adds GitHub build actions that are available to everyone who forks the repo. This also uses GitHub actions to validate PRs where possible rather than ADO for security reasons.
Also enables the GitHub Action based CodeQL and PREfast analysis.
> Added GitHub Actions for build and security analysis

- Audio/SoundCommon.cpp
- Inc/Audio.h
X3DAudio requires only 'real' values for floats, so values like INF or NAN will cause runtime faults. This PR adds an ``IsValid`` method that can be used on emitter and listener as part of a debug assert to check for these conditions.
This also provided a place to add additional validation of ranges for listener curves on emitters, as well as validate pChannelAzimuths usage.
> IsValid methods for AudioEmitter and AudioListener

- DirectXTK_Desktop_2019_Win10.vcxproj
- DirectXTK_Desktop_2022_Win10.vcxproj
- DirectXTK_GDK_2019.vcxproj
- DirectXTK_GDK_2022.vcxproj
- DirectXTK_Windows10_2022.vcxproj
Since CompileShaders might need ``WindowsSDKVersion`` this update passes that through.
> Update BWOI support in VC projects

- Src/ScreenGrab.cpp
Fixes /analyze warning that only happens when building for Xbox due to slight differences in system header SAL annotation.
```
ScreenGrab.cpp(39): warning C6388: '*pStaging' might not be '0':  this does not adhere to the specification for the function 'CaptureTexture'. 
ScreenGrab.cpp(39): warning C28196: The requirement that '*_Param_(6)==0' is not satisfied. (The expression does not evaluate to true.)
```
The requirement for a `_COM_OutPtr_` parameter is that if the function returns a failed HRESULT, the parameter should be returning null. These code changes ensure that this happens for all failure paths.
> Fix /analyze warning

- .github/dependabot.yml
- .github/workflows/vcpkg.yml
- CMakeLists.txt
- build/DirectXTK12-GitHub-GDK.yml
- build/DirectXTK12-GitHub-MinGW.yml
- build/DirectXTK12-GitHub-Test-Dev17.yml
- build/DirectXTK12-GitHub-Test.yml
- build/DirectXTK12-OneFuzz-Coverage.yml
- build/DirectXTK12-OneFuzz.yml
- build/DirectXTK12-SDL.yml
This PR makes sure ``assert`` macros in the library built for fuzz-testing remain in place even in release builds.
> Includes ADO YAML code review to clean up use of PATs, and to convert all use of vcpkg in the pipelines to 'manifest mode'.
> Also sets the dependabot to not spam quite so often for GHA.
> Keep asserts on in fuzz-testing builds

- Inc/RenderTargetState.h
Lets you do:
```
RenderTargetState rtState(m_msaaHelper4->GetBackBufferFormat(),
m_msaaHelper4->GetDepthBufferFormat(),
m_msaaHelper4->GetSampleCount());
```
> Add helper to RenderTargetState for MSAA

- Src/ScreenGrab.cpp
State transition handling when capturing MSAA resources which is supposed to get resolved was incorrect.
> Fixed state transitions for MSAA ScreenGrab

- Inc/DDSTextureLoader.h
- Src/DDSTextureLoader.cpp
Adds a flag option to DDSTextureLoader for only loading the first mip of a DDS file.
> This was added to DirectXTex as `DDS_FLAGS_IGNORE_MIPS` in July. It is useful for more than just corrupted files.
> Add DDS_LOADER_IGNORE_MIPS flag to DDSTextureLoader

- README.md
- build/DirectXTK12-GitHub-SDK-prerelease.yml
- build/DirectXTK12-GitHub-SDK-release.yml
As of Windows SDK version 10.0.26100.1834, ARM64 for Win32 "classic" Desktop no longer builds with the VS 2019 toolset. VS 2022 is required.
> VS 2019 Win32 on ARM64 is no longer supported

- Inc/Audio.h
- Inc/CommonStates.h
- Inc/DDSTextureLoader.h
- Inc/Effects.h
- Inc/GamePad.h
- Inc/GraphicsMemory.h
- Inc/Model.h
- Inc/Mouse.h
- Inc/PostProcess.h
- Inc/SpriteBatch.h
- Inc/WICTextureLoader.h
Originally I used `DWORD` for flags. When I removed Windows-specific types, I changed it to `unsigned long` to keep the signature the same. The ask is to use `uint32_t` instead which is more consistent on Windows vs. Linux.
Also removed 'extra-semi' for macro.
> Use fixed width integers for underlying enum types

- CMakeLists.txt
- Inc/DDSTextureLoader.h
- Inc/Model.h
- Inc/WICTextureLoader.h
- Inc/XboxDDSTextureLoader.h
- Src/DDSTextureLoader.cpp
- Src/WICTextureLoader.cpp
- Src/XboxDDSTextureLoader.cpp
When #274 was added to make the type of `FromMemory` operations use something other than `void*`, this turns out to result in code-breaks for clients using C++17's ``std::byte*``.
This PR adds compat inlines to avoid requiring the client code add casts.
> Minor tweak to CMake to avoid requiring all clients use directxmath and directx-headers packages externally.
> Support using C++17 std::byte for FromMemory functions

- CMakeLists.txt
For Win32 scenarios, DirectXMath and DirectX-Headers are optional for building. Even when using those packages to build the library, the client code can still choose to use the SDK version of those headers which works fine.
For MinGW, however, clients must always use the packages since the platform toolset don't include these headers (or at least not the right versions of them).
> Fix for CMake using MinGW

- Audio/SoundCommon.h
- Src/LoaderHelpers.h
I added some 'whitebox' testing of internal functions and it was resulting in link failures in some cases due to inconsistent calling conventions for the internal linkage. This decorates the internal free-functions for DirectX Tool Kit for Audio to make this linking robust.
> Also includes a minor update to use E_INVALIDARG
> Minor update to enable 'white box' testing of some internal functions

- .github/workflows/main.yml
- .github/workflows/uwp.yml
- .github/workflows/vcpkg.yml
- CMakePresets.json
Also adds MinGW64 and AArch64 (ARM64) Clang coverage to Git Hub Actions.
> Add GitHub Actions to validate UWP via CMake

- Audio/SoundStreamInstance.cpp
- Audio/WAVFileReader.cpp
- Audio/WaveBankReader.cpp
- Inc/Audio.h
- Inc/GamePad.h
- Src/BinaryReader.cpp
- Src/GamePad.cpp
- Src/LoaderHelpers.h
Removed Windows 7 support for *DirectX Tool Kit for Audio* and shared components with *DirectX Tool Kit for DX11*. That library now requires Windows 8.1 or later.
GamePad always uses XInput 1.4 rather than XInput 9.1.0
Always uses CreateFile2, GetOverlappedResultEx, and WIC2
> Note that Steam dropped support in January 2024 for Windows 7, Windows 8.0, and Windows 8.1 so this cleanup was overdue.
> Update shared components from DirectXTK

- Src/Mouse.cpp
Use USER_DEFAULT_SCREEN_DPI define instead of 96 value.
> Code review for Mouse CoreWindow implementation

- Audio/SoundCommon.cpp
- Audio/SoundStreamInstance.cpp
- Src/AlphaTestEffect.cpp
- Src/BufferHelpers.cpp
- Src/EffectTextureFactory.cpp
- Src/GeometricPrimitive.cpp
- Src/Geometry.cpp
- Src/LoaderHelpers.h
- Src/Model.cpp
- Src/ModelLoadCMO.cpp
- Src/ModelLoadSDKMESH.cpp
- Src/ModelLoadVBO.cpp
- Src/Mouse.cpp
- Src/NormalMapEffect.cpp
- Src/PBREffect.cpp
- Src/ResourceUploadBatch.cpp
- Src/SharedResourcePool.h
- Src/SpriteBatch.cpp
- Src/SpriteFont.cpp
- Src/WICTextureLoader.cpp
Both ``const auto`` and ``auto const`` are equivalent in terms of the C++ compiler parser, but general coding guidelines suggest using ``const auto``. The primary reason for this PR is to be consistent since the codebase was using both.
> Code review for const auto vs auto const

- build/DirectXTK12-GitHub-CMake.yml
- build/DirectXTK12-GitHub-Test-Dev17.yml
- build/DirectXTK12-GitHub-Test.yml
- build/DirectXTK12-GitHub.yml
Remove cases of building for ARM64 with VS 2019 due to changes to Windows SDK (26100).
Also cleans up the original #220 quick fix for UWP which should be building in the Dev17 pipeline.
> Update ADO coverage for clang v12 

- Inc/SimpleMath.h
- Inc/SimpleMath.inl
* Fixed regression in #307 with Vector2/Vector3 * operator with scalar float first.
* added `operator/(scalar, vector)` for Vector2, Vector3, Vector4
* added `operator/(scalar, matrix)` for Matrix
* some minor code review
> SimpleMath fixes for binary operator* with scalar

- .github/workflows/vcpkg.yml
- CMakePresets.json
- Inc/GamePad.h
- Src/GamePad.cpp
- Src/Keyboard.cpp
- Src/Mouse.cpp
- Src/pch.h
- build/vcpkg.json
The original GameInput implementation that is used for the Microsoft GDK is 'verison 0'. Version 1 of the API was released today via NuGet. This PR updates the implementation of GamePad, Keyboard, and Mouse to support both the old and new versions.
> GameInput implementation updates for for GAMEINPUT_API_VERSION = 1

- Audio/AudioEngine.cpp
- Audio/SoundCommon.cpp
- Audio/SoundCommon.h
- Inc/Audio.h
* Adds new audio engine flags
* `AudioEngine_DisableLFERedirect` will disable the current default behavior of using `X3DAUDIO_CALCULATE_REDIRECT_TO_LFE` if there is a LFE channel in the output.
* `AudioEngine_DisableDopplerEffect` will disable the current default use of  `X3DAUDIO_CALCULATE_DOPPLER` for all X3DAudio calculations.
* `AudioEngine_ZeroCenter3D` will add `X3DAUDIO_CALCULATE_ZEROCENTER` to all X3DAudio calculations.
* Adds new sound instance flags
* `SoundEffectInstance_UseRedirectLFE` internal flag now repurposed to force use of `X3DAUDIO_CALCULATE_REDIRECT_TO_LFE` per voice if not enabled globally and if there is a LFE channel in the output.
* `SoundEffectInstance_ZeroCenter3D` flag forces the use of  `X3DAUDIO_CALCULATE_ZEROCENTER` per voice if not enabled globally.
> Improve control for X3DAudio calculate flags

- build/DirectXTK12-GitHub-MinGW.yml
* Retired support for Windows 7 and Windows 8.0
* CMake project updates including support for BUILD_SHARED_LIBS (i.e. DLL vs. static library)
> Update ADO pipeline for MinGW validation

- .azuredevops/policies/approvercountpolicy.yml
- Audio/SoundCommon.h
- Inc/Audio.h
- Inc/BufferHelpers.h
- Inc/CommonStates.h
- Inc/DDSTextureLoader.h
- Inc/DescriptorHeap.h
- Inc/DirectXHelpers.h
- Inc/EffectPipelineStateDescription.h
- Inc/Effects.h
- Inc/GamePad.h
- Inc/GeometricPrimitive.h
- Inc/GraphicsMemory.h
- Inc/Keyboard.h
- Inc/Model.h
- Inc/Mouse.h
- Inc/PostProcess.h
- Inc/PrimitiveBatch.h
- Inc/RenderTargetState.h
- Inc/ResourceUploadBatch.h
- Inc/ScreenGrab.h
- Inc/SimpleMath.h
- Inc/SpriteBatch.h
- Inc/SpriteFont.h
- Inc/VertexTypes.h
- Inc/WICTextureLoader.h
- Inc/XboxDDSTextureLoader.h
CoPilot suggested a change which I disagreed with, but when I researched it a bit I realized there was a different change that would be useful to prefer `__attribute__` to `__declspec` for GNUC.
> Also includes some AzureDev Ops polices from the production pipelines.
> Code review feedback for DLL declimport/export

- .azuredevops/pipelines/DirectXTK12-GitHub-CMake-Dev17.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-CMake.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-Dev17.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-GDK-Dev17.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-GDK.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-MinGW.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-SDK-prerelease.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-SDK-release.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-Test-Dev17.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-Test.yml
- .azuredevops/pipelines/DirectXTK12-GitHub.yml
- .azuredevops/templates/DirectXTK12-build-gdk.yml
- .azuredevops/templates/DirectXTK12-build-uwp-arm64.yml
- .azuredevops/templates/DirectXTK12-build-uwp.yml
- .azuredevops/templates/DirectXTK12-build-win32.yml
- .github/workflows/codeql.yml
- .github/workflows/main.yml
- .github/workflows/msbuild.yml
- .github/workflows/msvc.yml
- .github/workflows/test.yml
- .github/workflows/uwp.yml
- .github/workflows/vcpkg.yml
- build/copysourcetree.flt
- build/copysourcetree.ps1
This PR adds the use of strategy and templates to the existing ADO pipelines.
* For the basic builds using Visual Studio MSBuild with minimal job setup, I made use of `strategy` `matrix` to simplify the pipelines for GitHub, GitHub-Dev17, GitHub-Test, and GitHub-Dev17.
* For the Windows SDK NuGet pipelines which have substantial package sizes as part of job setup, I made use of `template` for SDK-release and SDK-prerelease pipelines to share implementation.
> Also updated pipeline trigger path filters: GHA should ignore everything under ``.azuredevops``, and ADO should ignore everything under ``.github``.
> Cleanup of ADO pipeline YAML files

- Src/CMO.h
- Src/ModelLoadCMO.cpp
- Src/ModelLoadVBO.cpp
- Src/vbo.h
Minor updates to make CMO.h and VBO.h useful for DirectXMesh and UVAtlas.
> Update CMO and vbo headers

- .azuredevops/pipelines/DirectXTK12-GitHub-MinGW.yml
- CMakePresets.json
- build/vcpkg.json
The VCPKG pipelines were already validating the usage of *directx-headers* which covers the library. This makes sure *directx12-agility* is also covered in the test suite build.
> Add directx12-agilty to VCPKG tests

- .azuredevops/pipelines/DirectXTK12-GitHub-CMake.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-GDK-Dev17.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-GDK.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-Test-Dev17.yml
- .azuredevops/pipelines/DirectXTK12-GitHub-Test.yml
- .azuredevops/pipelines/DirectXTK12-GitHub.yml
- .github/copilot-instructions.md
- .github/linters/actionlint.yml
- .github/workflows/arm64.yml
- .github/workflows/arm64bvt.yml
- build/RestoreGDK.proj
- build/RestoreGDK.ps1
- build/SetupBWOI.cmd
- build/gdkedition.props
* GitHub Actions using Windows on ARM64 native
* Updated Azure pipelines to stop using the windows-2019 image while still testing the v142 platform toolset.
* Some minor updates for the GDK pipelines for the package renaming as of October 2024.
> GHA and ADO pipeline updates

- .nuget/directxtk12_desktop_2019.nuspec
- .nuget/directxtk12_desktop_2019.targets
- .nuget/directxtk12_desktop_win10.nuspec
- .nuget/directxtk12_desktop_win10.targets
- DirectXTK_Desktop_2019_Win10.vcxproj
- DirectXTK_Desktop_2022_Win10.vcxproj
Customers using the BinSkim Microsoft security tool will get flagged when using static C++ libraries not built using /Qspectre. This adds the alternative flavor of the libraries to the directxtex_desktop_2019 and directxtex_desktop_win10 versions of the NuGet package. The targets automatically selects the Spectre version when building with SpectreMitigations enabled.
> The new packages are 67 MB and 101 MB in size, compared to the old ones which were 32 MB and 48 MB.
> Add Spectre-mitigated libraries to the NuGet

- CMakeLists.txt
- CMakePresets.json
- Inc/DescriptorHeap.h
- Inc/GraphicsMemory.h
- README.md
- Src/GraphicsMemory.cpp
- Src/LoaderHelpers.h
- Src/PlatformHelpers.h
CMake 3.21 comes with VS 2022.
> VS 2019 users will need to install a standalone version of a CMake newer than the 3.20 that comes with it.
> Upgrade to CMake 3.21
